library(shiny)

shinyUI(fluidPage(

  # Application title
  titlePanel("Random data generation and ggplot2 smoother fit mini-game"),

  # Sidebar with a slider input for number of bins
  sidebarLayout(
    sidebarPanel(
      p('This application generates data set, plots data points and selected smoother.'),
      numericInput('points', 'Input number of data points', 100,
                   min = 1, max = 9999),
    radioButtons("fitType", "Select smoother type",
                 c("No fit"="none","Linear"="lin", 
                   "2-nd deegree polynom"="p2",
                   "3-rd degree polynom"="p3")),
    actionButton("generateButton", label = "Generate new data"),
    p(" "),
    p("Purpose of this application is to showcase ShinyApp building skills for 
    Course Project: Shiny Application and Reproducible Pitch."),
    h4("User can interact 
      with application following way:"),
    p("* Enter number of data points to be generated. Data is generated reactively upon entering 
      number of data points."),
    p("* Select method for data smoothing line. Line is generated reactively."),
    p("* Push 'Generate new data' button and denerate new dataset with 
      same number of data points and selected smoother."),
    p("Data is generated by custom build function."),
    p("Source code can be accessed here:
      ")
    ),

    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("pointPlot"),
      h4("Currently selected smoother:"),
      textOutput("modelrse")
    )
  )
))
